<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CitiesTableChunkSevenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('cities')->insert([
            0 => [
                'id' => 1462237,
                'name' => 'North Waziristan',
                'state_id' => 3173,
                'state_code' => '07',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => '2019-10-05 18:28:06',
                'updated_at' => '2019-10-05 18:28:06',
                'flag' => '1',
                'wikiDataId' => null,
            ],
            1 => [
                'id' => 1462238,
                'name' => 'Hunza',
                'state_id' => 3170,
                'state_code' => '07',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => '2019-10-05 18:28:06',
                'updated_at' => '2019-10-05 18:28:06',
                'flag' => '1',
                'wikiDataId' => null,
            ],
            2 => [
                'id' => 1462239,
                'name' => 'Shangla',
                'state_id' => 3171,
                'state_code' => '07',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => '2019-10-05 18:28:06',
                'updated_at' => '2019-10-05 18:28:06',
                'flag' => '1',
                'wikiDataId' => null,
            ],
            3 => [
                'id' => 1462240,
                'name' => 'South Waziristan',
                'state_id' => 3171,
                'state_code' => '07',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => '2019-10-05 18:28:06',
                'updated_at' => '2019-10-05 18:28:06',
                'flag' => '1',
                'wikiDataId' => null,
            ],
            4 => [
                'id' => 1462241,
                'name' => 'Jehlum',
                'state_id' => 3176,
                'state_code' => '07',
                'country_id' => 194,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => '2019-10-05 18:28:06',
                'updated_at' => '2019-10-05 18:28:06',
                'flag' => '1',
                'wikiDataId' => null,
            ],
            5 => [
                'id' => 1462242,
                'name' => 'Mirpur',
                'state_id' => 3172,
                'state_code' => '07',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => '2019-10-05 18:28:06',
                'updated_at' => '2019-10-05 18:28:06',
                'flag' => '1',
                'wikiDataId' => null,
            ],
            6 => [
                'id' => 1462243,
                'name' => 'Lower Orankzai',
                'state_id' => 3171,
                'state_code' => '07',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => '2019-10-05 18:28:06',
                'updated_at' => '2019-10-05 18:28:06',
                'flag' => '1',
                'wikiDataId' => null,
            ],
            7 => [
                'id' => 1462244,
                'name' => 'Mohmand',
                'state_id' => 3171,
                'state_code' => '07',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => '2019-10-05 18:28:06',
                'updated_at' => '2019-10-05 18:28:06',
                'flag' => '1',
                'wikiDataId' => null,
            ],
            8 => [
                'id' => 1462245,
                'name' => 'Zohab',
                'state_id' => 488,
                'state_code' => '07',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => '2019-10-05 18:28:06',
                'updated_at' => '2019-10-05 18:28:06',
                'flag' => '1',
                'wikiDataId' => null,
            ],
            9 => [
                'id' => 1462246,
                'name' => 'Mihtarlam',
                'state_id' => 3891,
                'state_code' => '07',
                'country_id' => 1,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => '2019-10-05 18:28:06',
                'updated_at' => '2019-10-05 18:28:06',
                'flag' => '1',
                'wikiDataId' => null,
            ],
            10 => [
                'id' => 1462247,
                'name' => 'North Waziristan Agency',
                'state_id' => 488,
                'state_code' => '07',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => '2019-10-05 18:28:06',
                'updated_at' => '2019-10-05 18:28:06',
                'flag' => '1',
                'wikiDataId' => null,
            ],
            11 => [
                'id' => 1462248,
                'name' => 'Cort Franca',
                'state_id' => 1705,
                'state_code' => '07',
                'country_id' => 107,
                'country_code' => 'IT',
                'latitude' => null,
                'longitude' => null,
                'created_at' => '2019-10-05 18:28:06',
                'updated_at' => '2019-10-05 18:28:06',
                'flag' => '1',
                'wikiDataId' => null,
            ],
            12 => [
                'id' => 1462249,
                'name' => 'Gujanwala',
                'state_id' => 3176,
                'state_code' => '07',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => '2019-10-05 18:28:06',
                'updated_at' => '2019-10-05 18:28:06',
                'flag' => '1',
                'wikiDataId' => null,
            ],
            13 => [
                'id' => 1462250,
                'name' => 'Muzafarabad',
                'state_id' => 3172,
                'state_code' => '07',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => '2019-10-05 18:28:06',
                'updated_at' => '2019-10-05 18:28:06',
                'flag' => '1',
                'wikiDataId' => null,
            ],
            14 => [
                'id' => 1462251,
                'name' => 'Bhimber',
                'state_id' => 3172,
                'state_code' => '07',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => '2019-10-05 18:28:06',
                'updated_at' => '2019-10-05 18:28:06',
                'flag' => '1',
                'wikiDataId' => null,
            ],
            15 => [
                'id' => 1462252,
                'name' => 'Charsada',
                'state_id' => 3171,
                'state_code' => '07',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => '2019-10-05 18:28:06',
                'updated_at' => '2019-10-05 18:28:06',
                'flag' => '1',
                'wikiDataId' => null,
            ],
            16 => [
                'id' => 1462253,
                'name' => 'Lakki Marwat',
                'state_id' => 3171,
                'state_code' => '07',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => '2019-10-05 18:28:06',
                'updated_at' => '2019-10-05 18:28:06',
                'flag' => '1',
                'wikiDataId' => null,
            ],
            17 => [
                'id' => 1462254,
                'name' => 'Sawabi',
                'state_id' => 3171,
                'state_code' => '07',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => '2019-10-05 18:28:06',
                'updated_at' => '2019-10-05 18:28:06',
                'flag' => '1',
                'wikiDataId' => null,
            ],
            18 => [
                'id' => 1462255,
                'name' => 'Qila Abdullah',
                'state_id' => 3174,
                'state_code' => '07',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => '2019-10-05 18:28:06',
                'updated_at' => '2019-10-05 18:28:06',
                'flag' => '1',
                'wikiDataId' => null,
            ],
            19 => [
                'id' => 1462256,
                'name' => 'Vehari',
                'state_id' => 3176,
                'state_code' => '07',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => '2019-10-05 18:28:06',
                'updated_at' => '2019-10-05 18:28:06',
                'flag' => '1',
                'wikiDataId' => null,
            ],
            20 => [
                'id' => 1462257,
                'name' => 'Gujrawanla',
                'state_id' => 3176,
                'state_code' => '07',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => '2019-10-05 18:28:06',
                'updated_at' => '2019-10-05 18:28:06',
                'flag' => '1',
                'wikiDataId' => null,
            ],
        ]);
    }
}
