<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitiesChunkSixSeeder extends Seeder
{
    public function run()
    {
        //

        $data = [
            [
                'id' => 146225,
                'name' => 'Lower Dir',
                'state_id' => 3171,
                'state_code' => 'LD',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => null,
            ],
            [
                'id' => 146226,
                'name' => 'Khurram',
                'state_id' => 3171,
                'state_code' => 'KA',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => null,
            ],
            [
                'id' => 146227,
                'name' => 'Akershus',
                'state_id' => 1422,
                'state_code' => 'PA',
                'country_id' => 233,
                'country_code' => 'US',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => null,
            ],
            [
                'id' => 146228,
                'name' => 'Neelam',
                'state_id' => 3172,
                'state_code' => 'NE',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => null,
            ],
            [
                'id' => 146229,
                'name' => 'Milton Keynes',
                'state_id' => 4916,
                'state_code' => 'NOR',
                'country_id' => 165,
                'country_code' => 'UK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => null,
            ],
            [
                'id' => 146230,
                'name' => 'Poonch',
                'state_id' => 3172,
                'state_code' => 'PO',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => null,
            ],
            [
                'id' => 146231,
                'name' => 'Taxila',
                'state_id' => 3176,
                'state_code' => 'TX',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => null,
            ],
            [
                'id' => 146232,
                'name' => 'Mandi Bahauddin',
                'state_id' => 3176,
                'state_code' => 'MB',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => null,
            ],
            [
                'id' => 146233,
                'name' => 'Salamat Pura',
                'state_id' => 3176,
                'state_code' => 'SP',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => null,
            ],
            [
                'id' => 146234,
                'name' => 'Orankzai',
                'state_id' => 3171,
                'state_code' => 'OK',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => null,
            ],
            [
                'id' => 1462235,
                'name' => 'Bagh',
                'state_id' => 3172,
                'state_code' => 'PA',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => null,
            ],
            [
                'id' => 1462236,
                'name' => 'Bagh',
                'state_id' => 3176,
                'state_code' => 'PA',
                'country_id' => 167,
                'country_code' => 'PK',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => null,
            ],

        ];

        foreach ($data as $item) {
            (new City())->create($item);
        }
    }
}
